POST http://localhost:7717/chat/call
Content-Type: application/json
X-User-Id: test
X-User-Token: test
X-CONVERSATION-ID: test_0

{
  "query": "你好，很高兴认识你，能简单介绍一下自己吗？"
}

###
GET http://localhost:7717/chat/history/test_0
Accept: application/json
X-User-Id: test
X-User-Token: test


