POST http://localhost:7717/chat/call
Content-Type: application/json
X-User-Id: test
X-User-Token: test
X-Conversation-Id: test_17

{
  "query": ""
}

###
GET http://localhost:7717/chat/history
Accept: application/json
X-User-Id: test
X-User-Token: test
X-Conversation-Id: test_9


